version: '3.5'

services:
  utopia-cms:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - $PWD:/utopia-cms
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mariadb:10.4.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=utopiacms
    - MYSQL_USER=utopiacms_user
    - MYSQL_PASSWORD=password
  
  db2:
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=utopiacms
    - MYSQL_USER=utopiacms_user
    - MYSQL_PASSWORD=password
    

  nginx:
    image: nginx
    restart: always
    volumes:
     - ./docs/nginx_example_conf/utopia-cms-dev.conf:/etc/nginx/nginx.conf
    ports:
     - 8080:80
    environment:
     - NGINX_PORT=80
    depends_on:
     - utopia-cms
